import pandas as pd
import os

def get_path_for_strat(strat):
    """
    Returns df_h, df_rl_summary, df_rl_traj.
    All data (heuristics and RL agent) are sourced from the same RL simulation.
    """
    if strat not in ["multiply", "evenly", "by_effort"]:
        raise ValueError(f"Invalid strategy: {strat}. Must be one of ['multiply', 'evenly', 'by_effort']")

    # Paths to files generated by process_rl_results.py
    rl_summary_file = f"../results/rl_summary_by_archetype_{strat}.parquet"
    rl_traj_file = f"../results/rl_trajectories_{strat}.parquet"

    # Check if the required RL result files exist
    if not all(os.path.exists(f) for f in [rl_summary_file, rl_traj_file]):
        print(f"Skipping {strat}: RL results files not found.")
        return None, None, None

    # 1. Load the full RL summary
    df_rl_all = pd.read_parquet(rl_summary_file)

    # 2. Load the detailed trajectories
    df_rl_traj = pd.read_parquet(rl_traj_file)

    # 3. df_rl_summary: RL agent data only
    df_rl_summary = df_rl_all[df_rl_all["archetype"] == "rl_agent"].copy()

    # 4. df_h: All other archetypes from the same simulation (serving as the baseline)
    # Filter out the 'rl_agent' so df_h only contains the heuristic policies
    df_h = df_rl_all[df_rl_all["archetype"] != "rl_agent"].copy()

    return df_h, df_rl_summary, df_rl_traj