import pandas as pd
import os

def get_path_for_strat(summary_path, trajectory_path):
    """Load and split heuristic and RL agent data from simulation results."""

    # Paths to files generated by process_rl_results.py
    rl_summary_file = summary_path
    rl_traj_file = trajectory_path

    # 1. Load the full summary
    df_rl_all = pd.read_parquet(rl_summary_file)

    # 2. Load the detailed trajectories
    df_rl_traj = pd.read_parquet(rl_traj_file)

    # 3. df_rl_summary: RL/Random agent data only
    # Support both 'rl_agent' and 'random' archetypes
    controlled_agent_archetypes = ["rl_agent", "random"]
    df_rl_summary = df_rl_all[df_rl_all["archetype"].isin(controlled_agent_archetypes)].copy()

    # 4. df_h: All other archetypes from the same simulation (serving as the baseline)
    # Filter out the controlled agent archetypes so df_h only contains the heuristic policies
    df_h = df_rl_all[~df_rl_all["archetype"].isin(controlled_agent_archetypes)].copy()

    return df_h, df_rl_summary, df_rl_traj